### ISSUE TITLE
Register this Package

### ISSUE THREAD

**Issue by rai-nhdaly** [RelationalAI-oss/LibSodium.jl#2]
@geokollias: Can we register this package with Julia? It's quite easy to do, and it would make using our system easier, since we wouldn't have to manually `Pkg.add()` this repository every time we want to start a new package that uses this.

Is there anything blocking us from registering? :) I see that the github readme lists that it isn't a complete implementation of the wrapper, but i don't see anything wrong with that!

I guess one question I have is how this relates to https://github.com/amitmurthy/Sodium.jl or https://github.com/Gnimuc/Sodium.jl? I think I remember that those did not expose the parts of `libsodium` that we needed, is that right? Would it make sense to merge this packages into `Sodium.jl`, then? Thanks!

**Comment by dewilson** [comment]
@geokollias any reason not to do this? I'm happy to take it on; I have a PR with a hacky workaround for the bootstrap script (https://github.com/RelationalAI/raicode/pull/3552), but it would be cool to just fix this instead of submitting it, since that PR has unintended side effects in some cases.

**Comment by geokollias** [comment]
@dewilson I think the main reason we didn't register it was my negligence :) Since you're already working on Julia stuff, sure, feel free to take it on! Thanks!

**Comment by rai-nhdaly** [comment]
@dewilson yeah i would love that! I think the remaining question we have was whether this can be merged into the existing Sodium repos?

I'm still not clear on what this package provides that those don't, and whether it would suit our needs to merge into one of them. Perhaps you could ask on one of their repos with an Issue? And/or we can ask on the julia slack? Thanks @dewilson - sorry this is a hassle.

If you don't want to do that, though, i don't see the harm in registering this package too. That's also an option.

**Comment by geokollias** [comment]
@rai-nhdaly Regarding the other two options:
- https://github.com/amitmurthy/Sodium.jl: It's quite old & unmaintained. It uses an old clang.jl version & I doubt it translates some libsodium macros properly.
- https://github.com/Gnimuc/Sodium.jl: I wasn't aware of it at the time! It seems it was created around the same time as ours. From a quick look, it seems it supports the two main libsodium functions we depend upon (`crypto_sign_ed25519_seed_keypair` & `crypto_sign_ed25519_detached`). We should probably test it.

**Comment by Gnimuc** [comment]
Hi guys, I'd like to transfer that package to this org because I'm actually not a user of that package(IIRC, I created that package for testing Clang.jl's wrapper generator and someone suggested registering as a package).

**Comment by rai-nhdaly** [comment]
Awesome, makes sense. Okay, whichever package we ultimately all settle on, it should probably move to the [JuliaWeb](https://github.com/JuliaWeb) organization.

Lemme ask about this on Slack.

**Comment by rai-nhdaly** [comment]
Per discussion on slack:
1. Yes, we should register this package. Maybe consider renaming to Sodium.jl.
2. Yes, we can move it to `JuliaWeb`. I'm asking now whether to do this before or after registering it.
    - @rbvermaa: I think you are probably the one who has to make the move. I do not believe I have the permissions to do so.

**Comment by Gnimuc** [comment]
Sodium.jl is a registered package and the submodule LibSodium is a superset of this package and is auto-generated with the new Clang.jl-v0.14.

**Comment by rai-nhdaly** [comment]
Oh, thanks @Gnimuc - i didn't realize! So we can probably actually just delete this package, since we created it without knowing about (or maybe before?) yours, but never registered it, and i think they do the same thing.


> Hi guys, I'd like to transfer that package to this org because I'm actually not a user of that package(IIRC, I created that package for testing Clang.jl's wrapper generator and someone suggested registering it as a package).

Since you want to transfer that package, i think you should transfer it to the JuliaWeb organization! @quinnj confirmed on slack that they'd be happy to take the package.

**Comment by Gnimuc** [comment]
hi @quinnj, I need permission to transfer the package to JuliaWeb.

**Comment by rai-nhdaly** [comment]
Okay, we've switched to `Sodium.jl` (the registered https://github.com/Gnimuc/Sodium.jl) and everything worked fine. I'm going to close this issue and mark the Repo deprecated. Thanks @Gnimuc!
